<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\School-Management-System\assets\app-logo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <LangVersion>latest</LangVersion>
    <RootNamespace>School_Management_System.Wpf</RootNamespace>
    <AssemblyName>School-Management-System.Wpf</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\School-Management-System\School-Management-System.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <None Include="App.config" />
    <Content Include="..\School-Management-System\assets\app-logo.ico">
      <Link>assets\app-logo.ico</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\School-Management-System\assets\brand-logo.png">
      <Link>assets\brand-logo.png</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\newbranding.png">
      <Link>assets\newbranding.png</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\companylogo.png">
      <Link>assets\companylogo.png</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\clientlogo.png">
      <Link>assets\clientlogo.png</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
