<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>assets\app-logo.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
    <RootNamespace>School_Management_System.Wpf</RootNamespace>
    <AssemblyName>School-Management-System.Wpf</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\School-Management-System\School-Management-System.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <None Include="App.config" />
    <Content Include="assets\app-logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\brand-logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
